# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  schedule:
    - cron: "0 12 * * 5"
  workflow_dispatch:

concurrency:
  group: data-update
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: lts
          cache: true

      - name: Run
        run: deno run -P ./main.ts

      - name: Check for modified files
        id: git-check
        run: |
            if [[ -n "$(git status --porcelain)" ]]; then
              echo "modified=true" >> $GITHUB_OUTPUT
            else
              echo "modified=false" >> $GITHUB_OUTPUT
            fi

      - name: Commit changes    
        if: steps.git-check.outputs.modified == 'true'
        run: |
            git config --global user.name 'fantasy0v0[Bot]'
            git config --global user.email 'fantasy0v0@users.noreply.github.com'
            git add -A
            git commit -m "🤖 Auto update data [$(date +'%Y-%m-%d')]"
            git pull --rebase
            git push

      - name: Generate Diff
        if: steps.git-check.outputs.modified == 'true'
        run: |
            git config diff.lfs.textconv cat
            { echo '```diff'; git --no-pager diff HEAD~1 | head -c 100000; echo '```'; } > diff.txt
            git --no-pager diff HEAD~1 > diff_full.txt

      - name: Release
        if: steps.git-check.outputs.modified == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: data-${{ github.run_id }}
          name: 📢 Update Diff
          body_path: diff.txt
          files: diff_full.txt
